// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title AstroPaymentReceiver
 * @notice Accepts ETH, USDT, and USDC deposits with a unique paymentId per transaction.
 *         Immediately forwards all funds to the immutable owner wallet.
 *         Emits a PaymentReceived event that the backend listener watches.
 *
 * Deployment:
 *   1. Open https://remix.ethereum.org
 *   2. Paste this file, compile with Solidity 0.8.20
 *   3. Deploy to Ethereum Mainnet with constructor arg = your owner wallet address
 *   4. Copy the deployed contract address and save it as CONTRACT_ADDRESS env var in Replit
 */

interface IERC20 {
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
}

contract AstroPaymentReceiver {
    address public immutable owner;

    // Emitted on every successful payment (ETH or ERC-20)
    // token = address(0) means native ETH
    event PaymentReceived(
        bytes32 indexed paymentId,
        address indexed sender,
        address token,
        uint256 amount
    );

    constructor(address _owner) {
        require(_owner != address(0), "Invalid owner");
        owner = _owner;
    }

    /**
     * @notice Deposit ETH. Call with msg.value = exact ETH amount.
     * @param paymentId  A unique identifier generated by the backend (bytes32).
     */
    function depositETH(bytes32 paymentId) external payable {
        require(msg.value > 0, "No ETH sent");
        (bool ok, ) = owner.call{value: msg.value}("");
        require(ok, "ETH forward failed");
        emit PaymentReceived(paymentId, msg.sender, address(0), msg.value);
    }

    /**
     * @notice Deposit an ERC-20 token (USDT or USDC).
     *         Caller must first approve this contract for `amount` on the token contract.
     * @param token     Token contract address (USDT or USDC on mainnet).
     * @param amount    Amount in the token's smallest unit (USDT/USDC use 6 decimals).
     * @param paymentId A unique identifier generated by the backend (bytes32).
     */
    function depositToken(
        address token,
        uint256 amount,
        bytes32 paymentId
    ) external {
        require(amount > 0, "Amount is 0");
        require(token != address(0), "Invalid token");
        bool ok = IERC20(token).transferFrom(msg.sender, owner, amount);
        require(ok, "Token transfer failed");
        emit PaymentReceived(paymentId, msg.sender, token, amount);
    }

    // Reject plain ETH transfers (must use depositETH)
    receive() external payable {
        revert("Use depositETH()");
    }
}
